"""added file uuid

Revision ID: b6e5e3a40a9e
Revises: 7ff0d799054c
Create Date: 2024-09-30 17:44:39.667271

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b6e5e3a40a9e"
down_revision: Union[str, None] = "7ff0d799054c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles",
        sa.Column("file_uuid", sa.String(), nullable=True, comment="УУИД фото"),
    )
    op.create_unique_constraint(None, "profiles", ["file_uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "profiles", type_="unique")
    op.drop_column("profiles", "file_uuid")
    # ### end Alembic commands ###
